<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Hamiltonian-for-modeling-kinetics-of-two-state-isomerization" data-toc-modified-id="Hamiltonian-for-modeling-kinetics-of-two-state-isomerization-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Hamiltonian for modeling kinetics of two state isomerization</a></span></li><li><span><a href="#Finding-the-equilibrium-points" data-toc-modified-id="Finding-the-equilibrium-points-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Finding the equilibrium points</a></span><ul class="toc-item"><li><span><a href="#Analytical-expression-for-the-energy-of-the-equilibrium-point-at-the-bottom-of-the-well" data-toc-modified-id="Analytical-expression-for-the-energy-of-the-equilibrium-point-at-the-bottom-of-the-well-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Analytical expression for the energy of the equilibrium point at the bottom of the well</a></span></li></ul></li></ul></div>

In [1]:
#!/usr/bin/env python3
"""
Created on Tue Feb 19 2019

@author: Shibabrat Naik
"""

import numpy as np

from matplotlib import cm
import matplotlib as mpl
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

from pylab import rcParams
mpl.rcParams['mathtext.fontset'] = 'cm'
mpl.rcParams['mathtext.rm'] = 'serif'
# mpl.rcParams['font.family'] = 'serif'
# mpl.rcParams['font.serif'] = ['Helvetica']

# plt.style.use('seaborn-white') # use sans-serif fonts

rcParams['figure.figsize'] = 5, 5

label_size = 25 #10, 20
mpl.rcParams['xtick.labelsize'] = label_size
mpl.rcParams['ytick.labelsize'] = label_size
mpl.rcParams['axes.labelsize'] = 25 #, 15

mpl.rcParams['axes.spines.left'] = True   ## display axis spines
mpl.rcParams['axes.spines.bottom'] = True
mpl.rcParams['axes.spines.top'] = True
mpl.rcParams['axes.spines.right'] = True
mpl.rcParams['xtick.top'] = True
mpl.rcParams['ytick.right'] = True
mpl.rcParams['xtick.direction'] = 'out'
mpl.rcParams['ytick.direction'] = 'out'
mpl.rcParams['xtick.major.size'] = 6
mpl.rcParams['ytick.major.size'] = 6
mpl.rcParams['xtick.major.width'] = 1.0
mpl.rcParams['ytick.major.width'] = 1.0


import DeLeonBerne2dof
import importlib
importlib.reload(DeLeonBerne2dof)
import DeLeonBerne2dof as DB2dof



### Hamiltonian for modeling kinetics of two state isomerization

Ref: De Leon and Berne, JCP [1981]; Gray and Rice, JCP [1987]

### Finding the equilibrium points 

In [2]:
from scipy import optimize
import DeLeonBerne2dof
import importlib
importlib.reload(DeLeonBerne2dof)
import DeLeonBerne2dof as DB2dof

#  mass A, mass B, epsilon, Dx, zeta, lambd = params
params =  (8, 8, 1.0, 10, 1.0, 1.5)
# params =  (8, 8, 1.0, 10, 2.30, 1.95)
# params =  (8, 8, 1.0, 10, 0, 1.95)
eq_pt_1 = optimize.fsolve(DB2dof.vec_field_DB, [0, 1, 0, 0], args = params, xtol = 1e-12, maxfev = 1000)
print(eq_pt_1)
eq_pt_2 = optimize.fsolve(DB2dof.vec_field_DB, [0, -1, 0, 0], args = params, xtol = 1e-12)
print(eq_pt_2)

# params =  (8, 8, 1.0, 10, 1.0, 1.5)
eq_pt_3 = optimize.fsolve(DB2dof.vec_field_DB, [0.1, 0.1, 0, 0], args = params)
print(eq_pt_3)


totalEnergyEqPt1 = DB2dof.V_DB(eq_pt_1[0], eq_pt_1[1], params[2:])
print(totalEnergyEqPt1)

[-3.25267761e-02  7.07106781e-01 -5.92188517e-32  4.91597874e-33]
[-3.25267761e-02 -7.07106781e-01 -1.51658044e-32 -3.42765391e-32]
[ 1.08635159e-17 -5.34552942e-51 -1.51929084e-64  5.93472984e-66]
[[-0.025]]


#### Analytical expression for the energy of the equilibrium point at the bottom of the well

In [3]:

total_energy_exp = params[3]*(1 - np.exp(-params[5]*eq_pt_1[0]))**2 - \
                    np.exp(-params[4]*params[5]*eq_pt_1[0]) + params[2]
print(total_energy_exp)



-0.02499999999999991


In [4]:

ls_tick = 20 #10, 20
ls_axes = 30
mpl.rcParams['xtick.labelsize'] = ls_tick
mpl.rcParams['ytick.labelsize'] = ls_tick
mpl.rcParams['axes.labelsize'] = ls_axes #, 15



def plot_PE_contours(xVec, yVec, params, ax_pes):            

    xMesh, yMesh = np.meshgrid(xVec, yVec)

    pe_surf = DB2dof.V_DB(xMesh, yMesh, params)
    pe_clines = np.logspace(0, 20, 100, endpoint = True)
    
#     plt.close('all')
#     fig_pes = plt.figure(figsize=(10,10))
#     ax_pes = fig_pes.gca()
#     cset = ax_pes.contour(xMesh, yMesh, np.log(pe_surf), 
#                            np.linspace(0, 30, 200, endpoint = True), 
#                            linewidths = 1.9, 
#                            cmap = cm.viridis, alpha = 0.9)
    
    cset = ax_pes.contour(xMesh, yMesh, pe_surf, \
                          pe_clines, linewidths = 1.5, \
                          cmap = cm.viridis, alpha = 0.9)

#     ax_pes = fig_pes.add_subplot(111, projection = '3d')
#     cset = ax_pes.plot_surface(xMesh, yMesh, pe_surf)
    
#     ax_pes.scatter(eq_pt_left[0], eq_pt_left[1], s = 40, c = 'r', marker = 'x')
#     ax_pes.scatter(eq_pt_right[0], eq_pt_right[1], s = 40, c = 'r', marker = 'x')
#     ax_pes.scatter(eq_pt_top[0], eq_pt_top[1], s = 40, c = 'r', marker = 'x')

#     ax_pes.set_aspect('equal')
#     ax_pes.set_ylabel(r'$y$', rotation = 0)
    ax_pes.set_xlabel(r'$x$')

    cbar = fig_pes.colorbar(cset, ticks = np.logspace(0, 30, 100, endpoint = True),
                            shrink = 0.7, pad = 0.05, 
                            drawedges = True)
#     cbar.set_label(r'$V_{DB}(x, y)$',fontsize = ls_axes)

    
    return 



### Figure to show the potential energy surface corresponding to parameters in Fig. 3 in De Leon-Berne (1981)

In [5]:

%matplotlib

label_size = 25 #10, 20
mpl.rcParams['xtick.labelsize'] = label_size
mpl.rcParams['ytick.labelsize'] = label_size
mpl.rcParams['axes.labelsize'] = 50 #, 15

xRes = 100
yRes = 150
# xVec = np.linspace(-2.5, 2.5, 100)
# yVec = np.linspace(-2.5, 2.5, 100)
xVec = np.linspace(-1.0, 1.0, xRes)
yVec = np.linspace(-1.5, 1.5, yRes)
# xVec = np.linspace(-0.3, 0.3, xRes)
# yVec = np.linspace(-1.2, 1.2, yRes)

# ordering of the parameters: mass A, mass B, epsilon, Dx, alpha (z in paper), lambd  
# params =  [1.0, 10, 1.0, 1.5]
# params =  (8.0, 8.0, 1.0, 10, 2.30, 1.95)
# params =  (8.0, 8.0, 1.0, 10, 1.00, 2.00)
params =  (8.0, 8.0, 1.0, 10, 1.00, 1.50)
# params =  (8.0, 8.0, 1.0, 10, 1.00, 1.30)
# params =  (8.0, 8.0, 1.0, 10, 1.00, 1.00)
# params =  (8.0, 8.0, 1.0, 10, 0.20, 1.00)

# file_name = 'pe_contour_param_set1'
file_name = 'pe_contour_param_fig3-B2x'

fig_pes = plt.figure(figsize=(10,10))
ax_pes = fig_pes.gca()
plot_PE_contours(xVec, yVec, params[2:], ax_pes)

eq_pt_1 = optimize.fsolve(DB2dof.vec_field_DB, [0, 1, 0, 0], args = params, \
                          xtol = 1e-12, maxfev = 1000)
eq_pt_2 = optimize.fsolve(DB2dof.vec_field_DB, [0, -1, 0, 0], args = params, \
                          xtol = 1e-12)
eq_pt_3 = optimize.fsolve(DB2dof.vec_field_DB, [0.1, 0.1, 0, 0], args = params)

ax_pes.scatter(eq_pt_1[0], eq_pt_1[1], 40, marker = 'o', c = 'r')
ax_pes.scatter(eq_pt_2[0], eq_pt_2[1], 40, marker = 'o', c = 'r')
ax_pes.scatter(eq_pt_3[0], eq_pt_3[1], 80, marker = 'X', c = 'r')

ax_pes.text(1.1,1.25,r'$\zeta = %.2f$' '\n' r'$\lambda = %.2f$'%(params[4],params[5]), \
            fontsize = label_size)

# pe = V_DB(xVec, yVec, params)

# np.savetxt('./data-figures/' + file_name + '.txt', params, header = "\epsilon,Dx,alpha,lambd")
# fig_pes.savefig('../../data/DeLeon-Berne/' + file_name + '.pdf', bbox_inches = 'tight')
# fig_pes.savefig('../../data-figures/DeLeon-Berne/pes-plots/' + file_name + '.pdf', bbox_inches = 'tight')




Using matplotlib backend: MacOSX


Text(1.1,1.25,'$\\zeta = 1.00$\n$\\lambda = 1.50$')

In [6]:
##!!!!!Something fishy here when calling the potential energy function!!!! 

%matplotlib

lambd_vec = [1.0, 1.00, 1.30, 1.50, 1.95, 2.00] # lambda
alpha_vec = [0.20, 1.00, 1.00, 1.00, 1.00, 2.30] # alpha

# fig_pes, ax_pes = plt.subplots(1, 2, sharex = True, sharey = True, figsize=(20,10))

# ordering of the parameters: mass A, mass B, epsilon, Dx, alpha (z in paper), lambd  
for (lambd,alpha) in enumerate(zip(lambd_vec[:2], alpha_vec[:2])):
    
    print(lambd,alpha)
    
    params =  (8.0, 8.0, 1.0, 10, alpha, lambd)
#     plot_PE_contours(xVec, yVec, params[2:], ax_pes[0])
#     pe_surf = DB2dof.V_DB(xMesh, yMesh, params[2:])
#     pe_vec = np.logspace(0, 10, 100, endpoint = True)

#     cset = axarr_pes[0].contour(xMesh, yMesh, pe_surf, 
#                                   pe_vec, linewidths = 1.2, \
#                                   cmap = cm.viridis, alpha = 0.9)



#     axarr_pes.plot(eq_pt_1[0], eq_pt_1[1], 'Xr', 
#                Markersize = 10)
#     axarr_pes.plot(eq_pt_2[0], eq_pt_2[1], 'Xr', 
#                Markersize = 10)
#     axarr_pes.plot(eq_pt_3[0], eq_pt_3[1], 'Xr', 
#                Markersize = 10)



Using matplotlib backend: MacOSX
0 (1.0, 0.2)
1 (1.0, 1.0)
